In [1]:
import pandas as pd
import numpy as np
import os
import seaborn as sns

In [2]:
#deduce genes differentially expressed when compared to k12 
#thresholds padj <= 0.0001, LFC >=2 


path = '/Users/bamudamaris/Library/CloudStorage/GoogleDrive-fufordamaris@gmail.com/My Drive/Data/DEG/DESeq2_output/'

full_table = None

for strain in os.listdir(path):
    if strain.startswith('NT'):
        df = pd.read_csv(path + strain)
        # filter data set for those with significant DEGs
        df = df[(df['log2FoldChange'].abs() >= 2) & (df['padj'] <= 0.0001)]
        # rename columns 
        df = df.rename(columns={'Unnamed: 0':'gene_id', 'log2FoldChange': strain[:-4]})
        # drop all irrelevant columns 
        df = df.set_index('gene_id').drop(columns=['baseMean', 'lfcSE', 'stat', 'pvalue', 'padj'], axis=1)
        # loop to merge multiple dataframes
        if full_table is None:
            full_table = df
        else:
            full_table = pd.merge(full_table, df, left_index=True, right_index=True, how='outer')

full_table.index = ["_".join(i.split("_cds_")[1].split("_")[:-1]) for i in full_table.index]            

# Count the occurrences of each gene being differentially expressed across strains
full_table.loc['Total_DEGs'] = full_table.notnull().sum()


full_table

,NT12044,NT12087,NT12285,NT12332,NT12130,NT12118,NT12119,NT12131,NT12521,NT12086,...,NT12507,NT12467,NT12498,NT12671,NT12670,NT12506,NT12089,NT12704,NT12510,NT12505
,2.791937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.612429,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-13.156652,NaN,NaN
,NaN,-7.399989,-7.443812,NaN,NaN,NaN,NaN,NaN,NaN,-6.737919,...,NaN,NaN,NaN,-5.656519,-4.093787,NaN,-4.435965,NaN,NaN,NaN
,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
YP_588470.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YP_588474.1,NaN,NaN,NaN,NaN,NaN,-3.40793,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,-3.772074,-3.373309,NaN,NaN,NaN,NaN,NaN
YP_588477.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6.257155,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
YP_588479.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total_DEGs,312.000000,297.000000,344.000000,140.0,296.0,362.00000,173.0,215.000000,3.0,298.000000,...,4.0,1.0,1.0,378.000000,301.000000,6.0,316.000000,45.000000,16.0,2.0

In [3]:
# Extract the Total_DEGs per strain
degs_count = full_table.loc['Total_DEGs'].reset_index()
degs_count.columns = ['Strain', 'Total_DEGs']
degs_count = degs_count.set_index('Strain')
degs_count

         Total_DEGs
Strain
NT12044       312.0
NT12087       297.0
NT12285       344.0
NT12332       140.0
NT12130       296.0
...             ...
NT12506         6.0
NT12089       316.0
NT12704        45.0
NT12510        16.0
NT12505         2.0

[116 rows x 1 columns]

In [4]:
strain_info = pd.read_csv('/Users/bamudamaris/Library/CloudStorage/GoogleDrive-fufordamaris@gmail.com/My Drive/Data/Datasets/mystrains.tsv', sep = '\t', index_col = 0)
strain_info.head(3)

,Strain name,Evolution Experiment?,Parental Strain,Alternative Strain Name,Full Strain Name After Genome Analysis,ENA Accession,Alternative Genome Source,Reference (PMID),Isolation origin,Year,Phenotype,German BSL level,Notes
Strain Identifier,,,,,,,,,,,,,
NT12447,B367,0,NaN,KC329,Escherichia coli B367,NaN,Broad institute Antibiotic resistance collection,NaN,Australian magpie Coffs,2001,Commensal strain,1.0,NaN
NT12619,S17,0,NaN,NaN,Escherichia coli S17,PRJNA189395,NaN,23516222,Broiler chick with septicemia,2013,Pathogenic strain,2.0,APEC
NT12460,TA464,0,NaN,KC342,Escherichia coli TA464,NaN,Broad institute Antibiotic resistance collection,NaN,Common wallaroo,1996,Commensal strain,1.0,NaN

In [5]:
merged = pd.read_csv('/Users/bamudamaris/Library/CloudStorage/GoogleDrive-fufordamaris@gmail.com/My Drive/Data/Datasets/deseqoutput_with_genenames.tsv', sep = '\t', index_col = 0)
merged

,NT12189,NT12177,NT12130,NT12150,NT12111,NT12131,NT12167,NT12023,NT12015,NT12146,...,NT12173,NT12176,NT12106,NT12095,NT12110,NT12096,NT12105,NT12136,NT12133,protein_id
gene_name,,,,,,,,,,,,,,,,,,,,,
thrA,-1.396155,-2.021794,-0.956499,-0.955567,-1.683656,-1.824484,0.098299,-1.159293,-1.545493,-1.568979,...,-2.618879,-1.823328,-1.256080,-1.770355,2.361559,-2.285443,-1.518675,-1.266543,-1.282496,NP_414543.1
thrB,-1.086905,-1.487570,-0.586719,-1.096873,-1.176046,-1.030935,0.393447,-0.781913,-1.198202,-1.274703,...,-1.822840,-1.691225,-1.391990,-1.339657,2.309845,-1.496152,-1.059097,-0.881015,-1.009158,NP_414544.1
thrC,-1.036221,-1.481607,-0.499014,-1.100753,-1.168859,-1.208431,0.211042,-0.621689,-1.178905,-1.253939,...,-1.516599,-1.356863,-1.423271,-1.507808,2.182499,-1.279540,-1.331691,-1.083987,-1.021967,NP_414545.1
yaaX,-1.127845,-0.445211,-1.345601,-2.542644,-2.384128,-1.393269,-0.704541,-1.196932,-0.805795,-4.195872,...,-1.470179,-2.691422,-2.232320,-1.213199,0.524975,-1.018777,-0.367529,-0.578661,-0.878953,NP_414546.1
yaaA,-0.170443,0.236060,0.244311,-0.585788,-0.006371,-0.011233,-0.012980,0.073378,0.031135,0.205472,...,0.127086,0.301302,-0.640534,-0.454320,-0.295649,0.125736,0.224585,0.050995,0.177193,NP_414547.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,0.357424,0.407631,0.430785,0.504160,0.214881,0.287156,0.478511,0.379188,0.420587,0.429609,...,0.139177,0.483007,0.298295,0.300719,0.349855,0.494350,0.346199,0.761291,0.219665,NP_418816.1
NaN,3.099915,0.086031,-0.603411,0.363925,0.631688,-0.382841,0.032728,-0.292673,0.041291,0.312853,...,0.535198,0.536943,-0.047159,2.975198,-0.293632,-0.166578,-0.123916,1.003094,0.560309,NP_418817.1
NaN,0.239958,0.108566,0.244223,0.008767,0.299795,-0.416000,0.002630,-0.058812,-0.156788,0.201081,...,0.192511,0.112204,-0.387683,-0.535587,-0.866010,-0.119510,-0.434823,-0.114681,0.090749,NP_418818.1
NaN,0.529843,0.537271,-0.138190,-0.695509,0.010163,0.137031,0.397660,0.071438,0.072998,0.062984,...,0.474563,-0.195993,-0.437971,-0.330971,-0.472149,0.081591,-0.238738,0.309960,0.209397,NP_418819.1
NaN,0.288563,0.573327,0.107360,-0.661217,0.189189,0.137145,-0.758377,0.099991,0.069366,-0.109693,...,0.648316,-0.362264,-0.395330,0.099177,0.377209,0.529572,-0.002349,-0.088530,0.158988,NP_418820.1

In [6]:
gpa = pd.read_csv('/Users/bamudamaris/ownCloud2/E.coli/panaroo/gene_presence_absence.Rtab', sep = '\t', index_col = 0)
gpa = gpa[gpa.index.isin(merged.index)]
gpa.columns = [x.split('_')[0] for x in gpa.columns]
gpa.loc['missing_genes'] = (gpa == 0.0).sum()
gpa

,NT12001,NT12002,NT12004,NT12007,NT12012,NT12015,NT12020,NT12021,NT12023,NT12025,...,NT12572,NT12573,NT12576,NT12616,NT12619,NT12670,NT12671,NT12704,NT12705,NT12879
Gene,,,,,,,,,,,,,,,,,,,,,
ydfJ,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
rpmA,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
ptsH,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
ybiJ,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
ilvM,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
thyA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
mukF,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
rapA,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
recF,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
missing_genes,35,136,43,478,316,381,223,281,227,238,...,321,238,265,475,92,277,272,272,272,309

In [7]:
# Extract the number of missing genes per strain
missing = gpa.loc['missing_genes'].reset_index()
missing.columns = ['Strain', 'missing_genes']
missing = missing.set_index('Strain')
missing

         missing_genes
Strain
NT12001             35
NT12002            136
NT12004             43
NT12007            478
NT12012            316
...                ...
NT12670            277
NT12671            272
NT12704            272
NT12705            272
NT12879            309

[117 rows x 1 columns]

In [8]:
data = pd.merge(degs_count, strain_info[['Phenotype','Strain name']], left_index = True, right_index = True, how = 'outer').fillna(0)
data = pd.merge(data, missing, left_index = True, right_index = True, how = 'inner')
data['Total_DEGs'] = data['Total_DEGs'].astype(int)
#data.to_csv('degs_counts.tsv', sep = '\t')
data

         Total_DEGs             Phenotype Strain name  missing_genes
NT12001           0     Laboratory strain      MG1655             35
NT12002         113     Laboratory strain      MC4100            136
NT12004          79     Laboratory strain     BW25113             43
NT12007         152      Commensal strain        ED1a            478
NT12012          25      Commensal strain          HS            316
...             ...                   ...         ...            ...
NT12670         301  Evolution experiment       1069A            277
NT12671         378  Evolution experiment       1069B            272
NT12704          45     Laboratory strain         606            272
NT12705          54     Laboratory strain         607            272
NT12879         293  Evolution experiment       11346            309

[117 rows x 4 columns]

In [29]:
#compute top variable genes across strains. 

# using vst normalised count. 
top = pd.read_csv('/Users/bamudamaris/Library/CloudStorage/GoogleDrive-fufordamaris@gmail.com/My Drive/Data/Datasets/vst_batch_corrected.tsv', sep = ',',index_col = 0)
#top.columns = [x.split('_')[0] for x in top.columns]
top.index = ["_".join(i.split("_cds_")[1].split("_")[:-1]) for i in top.index]
top

,NT12001_2,NT12002_2,NT12004_2,NT12015_2,NT12089_2,NT12095_2,NT12096_1,NT12098_1,NT12194_1,NT12192_1,...,NT12087_2,NT12087_3,NT12173_2,NT12173_3,NT12131_2,NT12131_3,NT12174_2,NT12174_3,NT12175_2,NT12175_3
NP_414543.1,11.956036,10.351602,11.636390,9.818209,9.679805,9.731596,9.208235,8.948139,8.828253,9.180399,...,9.710906,9.711258,9.109598,9.164270,9.757909,9.998491,8.369300,8.559117,8.945375,8.790959
NP_414544.1,10.391294,8.843748,10.007684,8.625423,8.803950,8.458924,8.077170,7.941022,8.050983,8.133907,...,8.515896,8.641429,8.257338,8.184166,8.911426,9.118595,8.580263,8.408415,7.716569,7.863247
NP_414545.1,11.272138,9.741850,10.895150,9.559255,9.599375,9.115897,9.179671,8.605313,8.771782,9.229593,...,9.241237,9.402333,9.198704,9.497878,9.452167,9.656606,9.321678,9.496642,8.706695,8.989417
NP_414546.1,6.208919,4.918682,5.428434,4.628484,4.770988,4.859930,4.471366,5.599075,4.440347,5.162262,...,5.678223,4.803775,4.847548,4.054835,4.972010,4.608523,5.002438,4.386822,5.706045,5.117174
NP_414547.1,8.999628,8.300938,8.688854,8.423516,7.756471,8.292513,9.288689,8.976046,8.462090,8.655016,...,8.833744,8.944674,8.830659,8.550887,8.575767,8.495919,8.621916,8.561573,8.164527,8.290328
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NP_418816.1,6.634252,6.988223,7.131122,7.145277,7.366499,7.132644,7.481283,7.460283,6.769028,7.329761,...,6.234663,5.913446,7.337809,6.957919,7.186413,7.373016,7.306227,6.887402,6.781834,6.474758
NP_418817.1,5.093570,5.241214,5.159771,5.428221,5.127779,8.666244,5.170060,5.471779,5.346994,5.546629,...,5.981490,5.531427,6.332289,5.909909,5.634656,5.204754,6.021329,5.624434,6.084467,5.786814
NP_418818.1,12.431500,11.634112,11.390189,11.538288,11.340155,11.553727,12.002459,12.245740,12.238933,11.674831,...,11.999755,12.164695,12.162812,12.415460,11.533108,11.691244,11.927321,12.181195,12.054943,12.279749
NP_418819.1,6.877614,6.747926,6.609757,6.638526,6.765006,6.874878,7.454199,8.067576,7.652419,6.888814,...,7.988225,6.978725,8.010806,7.276747,7.626103,6.988278,7.902758,7.053300,7.758758,7.597038
NP_418820.1,7.240317,7.280683,7.245848,7.343770,6.812166,7.587244,7.793375,7.377294,7.398709,7.667381,...,7.573617,7.411880,7.933157,7.904878,7.182774,7.241867,8.110850,8.171806,8.146759,8.142084

In [30]:
# Extract base sample names without the replicate suffix
base_sample_names = top.columns.str.rsplit('_', n=1).str[0]

# Average duplicate samples
averaged_exp = top.groupby(base_sample_names, axis=1).mean()

#compute standard deviation for each gene across the samples 
averaged_exp['std_dev'] = averaged_exp.std(axis=1)

# Sort by variability and select genes
top_var_genes = averaged_exp.sort_values(by='std_dev', ascending=False).head(50)
top_var_genes

,NT12001,NT12002,NT12004,NT12007,NT12012,NT12015,NT12020,NT12021,NT12023,NT12025,...,NT12573,NT12576,NT12616,NT12619,NT12670,NT12671,NT12704,NT12705,NT12879,std_dev
NP_418770.2,11.259726,11.604011,10.063312,2.932114,2.890191,5.894278,3.699605,2.866140,5.075097,4.247096,...,4.790592,3.251283,3.231329,2.656798,10.204533,10.402196,10.773785,10.424853,10.293843,3.182308
NP_416433.1,16.390358,10.392881,9.071004,3.574564,9.921974,9.144247,12.379721,10.673513,7.877384,6.063376,...,6.157136,7.136093,9.763410,8.525910,6.397780,5.610761,5.686735,3.727666,12.721993,3.118714
NP_418769.1,10.196736,10.332712,9.788019,2.323821,2.964148,5.124298,3.171544,2.026560,4.821428,4.091774,...,4.712718,3.761705,3.596348,2.540263,10.557312,10.679204,10.056702,9.662033,9.980459,3.062659
NP_416545.1,11.367367,11.432902,11.546043,2.740894,3.338556,7.213764,4.605532,2.834142,10.182563,6.301740,...,5.576438,5.382560,6.497169,2.644505,10.079235,9.869754,9.072895,9.262807,8.437824,3.010132
NP_416434.1,11.860929,7.108923,6.388780,3.544872,3.197855,7.932677,11.522101,11.005056,6.903119,4.335983,...,5.267492,8.867059,9.262781,2.653365,4.726341,3.740694,4.433853,2.802544,8.427590,2.962650
NP_416543.1,10.694758,10.669840,10.869960,2.983108,3.127505,6.554963,4.436490,2.490484,8.654212,5.681507,...,4.381096,4.214927,6.290752,2.805140,5.716753,4.209699,3.870804,2.736361,8.024603,2.902847
NP_418768.1,9.541116,9.731031,9.120944,2.179949,2.555544,4.902405,2.826866,2.179949,4.625453,4.498038,...,3.791136,3.754071,3.360832,2.042409,12.223248,12.400956,11.153396,10.907131,10.780787,2.899017
NP_418711.1,11.856800,11.936009,12.245965,12.122647,4.041919,7.580954,5.934720,3.332138,10.103915,10.728151,...,12.450108,11.013477,9.598895,12.286760,12.463531,12.712158,12.375125,11.412617,13.360405,2.834271
NP_415501.1,7.124615,6.868698,7.850834,3.069585,10.364782,10.802451,7.120913,7.975632,10.701769,11.394690,...,6.876531,6.860916,4.075302,7.868164,7.542240,7.384987,7.675231,7.757343,7.425473,2.829762
,11.494447,12.463901,11.558196,4.739267,3.613003,8.458331,6.737032,3.482327,9.382040,13.994592,...,7.955220,6.347232,13.455955,15.109475,8.709535,8.418249,9.778124,8.927992,8.729612,2.826810
NP_416541.1,10.856405,10.963236,11.396091,2.167195,2.395430,6.609795,2.830913,1.869935,6.301622,5.255636,...,4.204289,3.783826,2.893897,2.711495,4.393657,4.112390,3.273844,2.547041,8.205231,2.805150
NP_418715.2,9.243527,9.132650,8.876887,2.483091,2.591068,5.776036,3.031237,2.731799,6.411205,9.561881,...,9.726424,3.570697,5.948192,1.962973,4.442347,3.409146,2.536590,2.259737,6.284367,2.791700
NP_416544.1,10.792952,10.876882,11.006228,2.575688,3.161622,6.957633,4.246292,2.716507,9.981635,6.070778,...,5.078221,4.784750,6.241812,2.709167,8.302564,7.854595,7.068506,7.050209,7.994832,2.789839
NP_416599.2,12.796698,13.546802,12.427904,2.531895,3.554012,8.415995,5.067353,3.666484,7.788856,6.305526,...,3.797547,3.951274,3.566665,3.065595,4.450593,4.782667,4.397528,4.045954,10.039097,2.788243
NP_416538.1,11.033035,11.021744,11.192534,2.280220,2.565587,6.344031,3.107697,2.594792,6.320783,5.193570,...,3.566080,3.796245,3.301286,2.696303,4.175911,4.168439,2.718842,2.821728,8.414823,2.787988
NP_416598.1,12.868936,13.931006,12.704777,2.916232,4.514330,8.764487,5.543139,2.970515,7.885738,6.021344,...,4.254617,4.497245,4.162999,2.903458,4.867391,4.947247,4.542013,4.446365,10.204359,2.737731
NP_418734.1,10.764036,6.844401,10.480789,3.903688,10.651298,7.108742,4.134336,3.372682,7.567129,6.513472,...,6.179284,5.118705,8.975705,7.882159,6.622633,6.800053,5.837671,4.195776,7.374790,2.733913
NP_418775.1,13.703752,8.631116,7.824112,4.858890,12.287316,8.122013,12.268586,11.145634,7.640184,6.901790,...,7.246450,7.318503,10.116579,10.550277,6.899878,6.454856,6.267236,5.310802,10.319570,2.731658
NP_416536.1,10.907215,10.954257,11.010902,2.265790,1.968530,6.108087,2.914741,1.968530,6.164159,4.795469,...,3.502389,3.502389,2.191290,2.809584,4.112220,4.143864,3.119072,2.467223,8.354658,2.709484
NP_418089.1,9.872139,9.937528,9.845091,1.971310,2.608331,6.355028,2.750971,1.971310,9.860978,6.152774,...,3.228543,4.051029,2.495449,6.864721,4.943613,4.222034,3.016612,2.661243,7.201417,2.682556
NP_418075.2,9.046709,8.458950,8.543441,9.518150,2.782256,9.105284,2.991038,2.782256,8.734141,10.516500,...,4.592078,3.311728,3.758907,3.483665,5.020193,4.413264,3.323095,3.384009,6.516693,2.668642
NP_416400.1,12.375892,7.208682,6.221728,4.206080,10.481859,7.485015,10.607497,9.476978,6.444357,5.366544,...,4.949241,4.669158,8.494054,9.021546,5.376321,4.594914,5.047459,3.380189,8.815538,2.665517
NP_415089.1,8.954854,8.439997,8.616248,3.011263,3.239484,9.617379,4.281551,3.122263,8.315138,10.238318,...,11.134178,7.372745,7.438892,11.421220,10.421055,10.615852,11.641987,11.427354,6.247987,2.660734
NP_416852.1,10.682683,10.359363,10.295906,1.827821,2.464842,6.067592,3.046427,1.827821,5.837639,4.626841,...,3.945945,3.646559,2.806106,6.865263,4.113219,4.047281,3.122559,2.204350,8.108591,2.627665
NP_416540.1,10.523922,10.171378,10.466800,1.947912,2.584932,6.653563,3.457340,1.947912,6.235960,5.329791,...,3.568114,3.798279,2.777722,2.666251,4.034774,4.028924,3.107627,2.754161,8.259061,2.626361
NP_416539.1,10.486034,10.262551,10.722167,2.320499,3.045355,6.300162,2.950551,2.023238,5.972844,4.925450,...,3.488854,3.488854,2.614952,2.530736,4.174958,3.949665,3.276525,2.630463,8.027873,2.617159
NP_416895.2,9.190251,10.089357,9.202928,2.011850,8.210039,5.910401,7.918526,8.016837,8.585453,10.305244,...,3.825065,7.650479,2.641658,8.060072,8.698943,8.852799,8.932849,8.904137,9.838256,2.610441
NP_414557.1,9.190251,10.089357,9.202928,2.011850,8.210039,5.910401,7.918526,8.016837,8.585453,10.305244,...,3.825065,7.650479,2.641658,8.060072,8.698943,8.852799,8.932849,8.904137,9.838256,2.610441
NP_415114.1,9.190251,10.089357,9.202928,2.011850,8.210039,5.910401,7.918526,8.016837,8.585453,10.305244,...,3.825065,7.650479,2.641658,8.060072,8.698943,8.852799,8.932849,8.904137,9.838256,2.610441
NP_415504.1,6.056979,5.723480,7.054481,3.000285,10.397632,10.078664,5.837472,6.814979,10.057240,10.826149,...,5.738921,4.773443,3.136916,6.722149,6.181374,6.117749,5.881904,5.969419,6.116805,2.607530
NP_418079.1,9.863434,9.540724,9.515224,2.108664,2.108664,6.097053,2.392479,2.460208,9.685817,5.753266,...,3.226908,3.698339,2.031630,2.717198,3.932297,4.016152,2.939947,2.579717,7.102794,2.589173
NP_418766.4,8.649759,8.455171,8.155667,2.233634,2.609229,5.021934,2.678551,2.233634,4.379501,3.795330,...,3.780877,2.819762,3.204530,1.721992,8.982187,9.156114,8.201235,7.861264,8.626945,2.583008
NP_418088.1,9.593881,9.575539,9.589743,2.452180,2.763028,6.081588,2.773303,2.034662,9.611618,6.339199,...,3.555959,3.651958,2.803074,5.881962,4.339174,4.112989,2.636035,2.421682,6.750258,2.575039
NP_418085.2,9.122916,9.397583,9.278603,1.901072,1.901072,5.877233,3.122905,1.901072,9.220412,5.458035,...,3.078753,3.790233,2.699904,7.152428,4.431175,4.072243,2.649897,2.301180,6.528235,2.568066
NP_415097.1,12.292055,11.929412,11.337290,5.975237,3.267677,10.650294,4.443405,1.880131,8.048240,5.698360,...,10.640896,5.378139,8.525214,9.498033,9.908983,9.997071,10.279140,10.394709,9.774510,2.550374
NP_416542.1,9.991972,10.136315,10.331716,1.934621,2.310216,5.804991,2.883568,1.934621,5.593899,4.761270,...,3.676638,3.676638,2.063680,2.825247,4.143298,4.005202,2.979922,2.612702,7.367620,2.550099
NP_416448.1,11.598188,6.498697,7.044481,4.842743,11.414006,8.319855,11.068918,10.632894,8.549099,5.538845,...,6.401119,4.422239,10.400075,9.931334,5.585156,5.400275,4.074030,2.125622,8.506058,2.542029
YP_009518741.1,6.427801,6.794972,6.802893,10.752340,3.089822,4.946999,3.009548,2.714228,7.661076,10.676916,...,5.245844,2.617728,2.843398,8.120426,4.302627,3.823101,2.989355,2.585057,4.174792,2.539815
NP_418083.1,9.274455,9.416390,9.285037,2.035288,2.035288,5.659905,2.743625,2.035288,9.152742,5.884407,...,2.996050,3.636298,2.079379,6.411590,4.434291,4.029297,2.422089,2.271519,6.360561,2.536068
NP_418710.4,10.084850,10.139668,10.428375,10.348114,3.410466,5.818771,4.994215,3.231332,8.454037,9.113081,...,10.731427,9.645362,8.165754,10.437188,10.444397,10.552438,10.366699,9.446728,11.132207,2.533922
NP_415507.2,4.824740,4.595991,5.965734,3.367210,9.757511,8.423168,5.535249,6.030805,9.948673,10.917643,...,4.610334,6.874694,3.966072,6.141924,4.422475,4.339112,4.342689,4.547540,3.764245,2.531368
NP_416537.1,10.075850,10.102636,10.168892,2.029919,2.666940,5.706694,2.497570,2.029919,5.685715,5.091527,...,3.515937,3.515937,1.863275,2.196564,4.082797,4.075800,2.931025,2.676269,7.482124,2.529281
NP_415503.1,5.552765,5.334338,6.373494,3.089241,8.974326,9.600315,5.603255,6.577975,9.636967,10.311895,...,5.442001,4.855385,3.738522,6.465057,5.538769,5.474669,5.417022,5.604204,5.000135,2.518667
NP_418802.1,8.847252,9.129465,8.755120,7.751157,3.147074,5.515177,3.776949,2.418709,6.508953,9.601940,...,4.169311,4.010454,2.117350,3.426180,4.394470,3.803128,2.805510,3.199773,6.194795,2.500495
,10.052129,10.010634,10.095620,1.852114,2.377609,5.905358,2.321425,1.852114,5.795071,4.240161,...,3.437792,3.437792,2.282374,2.616717,4.004652,3.766356,2.453486,2.365540,7.580800,2.498362
NP_418771.1,8.540691,8.762210,8.190937,2.249965,2.775460,4.694507,2.736008,2.249965,4.207292,3.330184,...,3.537709,2.816594,2.499460,2.000470,7.939263,8.291445,7.580820,7.316302,7.558822,2.468895
NP_417982.2,11.308136,6.321138,5.752861,3.573896,10.212110,6.113525,10.330200,9.119335,5.971127,5.124940,...,5.212400,5.458893,7.989479,8.426991,5.251355,4.868754,4.032680,3.257438,7.945121,2.465733
NP_416455.1,11.736207,7.107545,7.384242,4.611680,11.273434,8.784380,11.584723,11.258245,8.548498,5.745908,...,6.657241,4.137971,10.381715,9.965343,5.774982,5.269652,4.205784,2.425320,8.529550,2.460380
NP_417119.1,10.465472,10.400217,10.108056,2.194099,2.569693,6.110221,3.029419,2.194099,5.516638,4.469041,...,3.170779,3.400945,2.815933,2.561717,3.891246,3.730642,3.025381,2.771203,7.931767,2.459096
NP_416402.1,12.761935,8.045348,7.103206,5.442081,11.448220,8.170042,11.509529,10.338020,7.286473,6.299037,...,6.961466,7.257997,9.370213,9.639765,6.644474,6.166178,5.826410,4.909634,9.544407,2.440249

In [31]:
common_elements = list(set(full_table.index) & set(top_var_genes.index))

top50 = top_var_genes[top_var_genes.index.isin(common_elements)].T.drop('std_dev')

In [32]:
genes = pd.read_csv('/Users/bamudamaris/Library/CloudStorage/GoogleDrive-fufordamaris@gmail.com/My Drive/Data/Datasets/gene_positions.txt', sep = '\t', index_col = 1)
genes

               locus_tag gene_name strand    start      end
protein_id
NP_414542.1        b0001      thrL      +      189      255
NP_414543.1        b0002      thrA      +      336     2799
NP_414544.1        b0003      thrB      +     2800     3733
NP_414545.1        b0004      thrC      +     3733     5020
NP_414546.1        b0005      yaaX      +     5233     5530
...                  ...       ...    ...      ...      ...
NP_418742.1        b4322      uxuA      +  4551635  4552820
NP_418743.1        b4323      uxuB      +  4552900  4554361
NP_418744.1        b4324      uxuR      +  4554575  4555349
NP_418745.3        b4325      yjiC      -  4555489  4556320
YP_009518830.1     b4720      ytiC      +  4556573  4556675

[4279 rows x 5 columns]

In [28]:
top50 = top50.T
top50= pd.merge(top50, genes['gene_name'], left_index = True, right_index = True, how = 'left')
top50
#top50.to_csv('top_var_50.tsv', sep = '\t')

,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,gene_name
,11.494447,12.463901,11.558196,4.739267,3.613003,8.458331,6.737032,3.482327,9.38204,13.994592,...,6.347232,13.455955,15.109475,8.709535,8.418249,9.778124,8.927992,8.729612,NaN,NaN
,10.052129,10.010634,10.09562,1.852114,2.377609,5.905358,2.321425,1.852114,5.795071,4.240161,...,3.437792,2.282374,2.616717,4.004652,3.766356,2.453486,2.36554,7.5808,NaN,NaN
NP_414557.1,9.190251,10.089357,9.202928,2.01185,8.210039,5.910401,7.918526,8.016837,8.585453,10.305244,...,7.650479,2.641658,8.060072,8.698943,8.852799,8.932849,8.904137,9.838256,insL-1,insL-1
NP_415089.1,8.954854,8.439997,8.616248,3.011263,3.239484,9.617379,4.281551,3.122263,8.315138,10.238318,...,7.372745,7.438892,11.42122,10.421055,10.615852,11.641987,11.427354,6.247987,borD,borD
NP_415097.1,12.292055,11.929412,11.33729,5.975237,3.267677,10.650294,4.443405,1.880131,8.04824,5.69836,...,5.378139,8.525214,9.498033,9.908983,9.997071,10.27914,10.394709,9.77451,ompT,ompT
NP_415114.1,9.190251,10.089357,9.202928,2.01185,8.210039,5.910401,7.918526,8.016837,8.585453,10.305244,...,7.650479,2.641658,8.060072,8.698943,8.852799,8.932849,8.904137,9.838256,insL-2,insL-2
NP_415501.1,7.124615,6.868698,7.850834,3.069585,10.364782,10.802451,7.120913,7.975632,10.701769,11.39469,...,6.860916,4.075302,7.868164,7.54224,7.384987,7.675231,7.757343,7.425473,etk,etk
NP_415503.1,5.552765,5.334338,6.373494,3.089241,8.974326,9.600315,5.603255,6.577975,9.636967,10.311895,...,4.855385,3.738522,6.465057,5.538769,5.474669,5.417022,5.604204,5.000135,gfcE,gfcE
NP_415504.1,6.056979,5.72348,7.054481,3.000285,10.397632,10.078664,5.837472,6.814979,10.05724,10.826149,...,4.773443,3.136916,6.722149,6.181374,6.117749,5.881904,5.969419,6.116805,gfcD,gfcD
NP_415507.2,4.82474,4.595991,5.965734,3.36721,9.757511,8.423168,5.535249,6.030805,9.948673,10.917643,...,6.874694,3.966072,6.141924,4.422475,4.339112,4.342689,4.54754,3.764245,gfcA,gfcA
NP_416400.1,12.375892,7.208682,6.221728,4.20608,10.481859,7.485015,10.607497,9.476978,6.444357,5.366544,...,4.669158,8.494054,9.021546,5.376321,4.594914,5.047459,3.380189,8.815538,tar,tar
NP_416402.1,12.761935,8.045348,7.103206,5.442081,11.44822,8.170042,11.509529,10.33802,7.286473,6.299037,...,7.257997,9.370213,9.639765,6.644474,6.166178,5.82641,4.909634,9.544407,cheA,cheA
NP_416433.1,16.390358,10.392881,9.071004,3.574564,9.921974,9.144247,12.379721,10.673513,7.877384,6.063376,...,7.136093,9.76341,8.52591,6.39778,5.610761,5.686735,3.727666,12.721993,fliC,fliC
NP_416434.1,11.860929,7.108923,6.38878,3.544872,3.197855,7.932677,11.522101,11.005056,6.903119,4.335983,...,8.867059,9.262781,2.653365,4.726341,3.740694,4.433853,2.802544,8.42759,fliD,fliD
NP_416448.1,11.598188,6.498697,7.044481,4.842743,11.414006,8.319855,11.068918,10.632894,8.549099,5.538845,...,4.422239,10.400075,9.931334,5.585156,5.400275,4.07403,2.125622,8.506058,fliF,fliF
NP_416455.1,11.736207,7.107545,7.384242,4.61168,11.273434,8.78438,11.584723,11.258245,8.548498,5.745908,...,4.137971,10.381715,9.965343,5.774982,5.269652,4.205784,2.42532,8.52955,fliM,fliM
NP_416536.1,10.907215,10.954257,11.010902,2.26579,1.96853,6.108087,2.914741,1.96853,6.164159,4.795469,...,3.502389,2.19129,2.809584,4.11222,4.143864,3.119072,2.467223,8.354658,wbbK,wbbK
NP_416537.1,10.07585,10.102636,10.168892,2.029919,2.66694,5.706694,2.49757,2.029919,5.685715,5.091527,...,3.515937,1.863275,2.196564,4.082797,4.0758,2.931025,2.676269,7.482124,wbbJ,wbbJ
NP_416538.1,11.033035,11.021744,11.192534,2.28022,2.565587,6.344031,3.107697,2.594792,6.320783,5.19357,...,3.796245,3.301286,2.696303,4.175911,4.168439,2.718842,2.821728,8.414823,wbbI,wbbI
NP_416539.1,10.486034,10.262551,10.722167,2.320499,3.045355,6.300162,2.950551,2.023238,5.972844,4.92545,...,3.488854,2.614952,2.530736,4.174958,3.949665,3.276525,2.630463,8.027873,wbbH,wbbH
NP_416540.1,10.523922,10.171378,10.4668,1.947912,2.584932,6.653563,3.45734,1.947912,6.23596,5.329791,...,3.798279,2.777722,2.666251,4.034774,4.028924,3.107627,2.754161,8.259061,glf,glf
NP_416541.1,10.856405,10.963236,11.396091,2.167195,2.39543,6.609795,2.830913,1.869935,6.301622,5.255636,...,3.783826,2.893897,2.711495,4.393657,4.11239,3.273844,2.547041,8.205231,rfbX,rfbX
NP_416542.1,9.991972,10.136315,10.331716,1.934621,2.310216,5.804991,2.883568,1.934621,5.593899,4.76127,...,3.676638,2.06368,2.825247,4.143298,4.005202,2.979922,2.612702,7.36762,rfbC,rfbC
NP_416543.1,10.694758,10.66984,10.86996,2.983108,3.127505,6.554963,4.43649,2.490484,8.654212,5.681507,...,4.214927,6.290752,2.80514,5.716753,4.209699,3.870804,2.736361,8.024603,rfbA,rfbA
NP_416544.1,10.792952,10.876882,11.006228,2.575688,3.161622,6.957633,4.246292,2.716507,9.981635,6.070778,...,4.78475,6.241812,2.709167,8.302564,7.854595,7.068506,7.050209,7.994832,rfbD,rfbD
NP_416545.1,11.367367,11.432902,11.546043,2.740894,3.338556,7.213764,4.605532,2.834142,10.182563,6.30174,...,5.38256,6.497169,2.644505,10.079235,9.869754,9.072895,9.262807,8.437824,rfbB,rfbB
NP_416598.1,12.868936,13.931006,12.704777,2.916232,4.51433,8.764487,5.543139,2.970515,7.885738,6.021344,...,4.497245,4.162999,2.903458,4.867391,4.947247,4.542013,4.446365,10.204359,gatZ,gatZ
NP_416599.2,12.796698,13.546802,12.427904,2.531895,3.554012,8.415995,5.067353,3.666484,7.788856,6.305526,...,3.951274,3.566665,3.065595,4.450593,4.782667,4.397528,4.045954,10.039097,gatY,gatY
NP_416852.1,10.682683,10.359363,10.295906,1.827821,2.464842,6.067592,3.046427,1.827821,5.837639,4.626841,...,3.646559,2.806106,6.865263,4.113219,4.047281,3.122559,2.20435,8.108591,yfdH,yfdH
NP_416895.2,9.190251,10.089357,9.202928,2.01185,8.210039,5.910401,7.918526,8.016837,8.585453,10.305244,...,7.650479,2.641658,8.060072,8.698943,8.852799,8.932849,8.904137,9.838256,insL-3,insL-3
NP_417119.1,10.465472,10.400217,10.108056,2.194099,2.569693,6.110221,3.029419,2.194099,5.516638,4.469041,...,3.400945,2.815933,2.561717,3.891246,3.730642,3.025381,2.771203,7.931767,rnlA,rnlA
NP_417982.2,11.308136,6.321138,5.752861,3.573896,10.21211,6.113525,10.3302,9.119335,5.971127,5.12494,...,5.458893,7.989479,8.426991,5.251355,4.868754,4.03268,3.257438,7.945121,pdeH,pdeH
NP_418075.2,9.046709,8.45895,8.543441,9.51815,2.782256,9.105284,2.991038,2.782256,8.734141,10.5165,...,3.311728,3.758907,3.483665,5.020193,4.413264,3.323095,3.384009,6.516693,htrL,htrL
NP_418079.1,9.863434,9.540724,9.515224,2.108664,2.108664,6.097053,2.392479,2.460208,9.685817,5.753266,...,3.698339,2.03163,2.717198,3.932297,4.016152,2.939947,2.579717,7.102794,waaL,waaL
NP_418083.1,9.274455,9.41639,9.285037,2.035288,2.035288,5.659905,2.743625,2.035288,9.152742,5.884407,...,3.636298,2.079379,6.41159,4.434291,4.029297,2.422089,2.271519,6.360561,waaJ,waaJ
NP_418085.2,9.122916,9.397583,9.278603,1.901072,1.901072,5.877233,3.122905,1.901072,9.220412,5.458035,...,3.790233,2.699904,7.152428,4.431175,4.072243,2.649897,2.30118,6.528235,waaB,waaB
NP_418088.1,9.593881,9.575539,9.589743,2.45218,2.763028,6.081588,2.773303,2.034662,9.611618,6.339199,...,3.651958,2.803074,5.881962,4.339174,4.112989,2.636035,2.421682,6.750258,waaG,waaG
NP_418089.1,9.872139,9.937528,9.845091,1.97131,2.608331,6.355028,2.750971,1.97131,9.860978,6.152774,...,4.051029,2.495449,6.864721,4.943613,4.222034,3.016612,2.661243,7.201417,waaQ,waaQ
NP_418710.4,10.08485,10.139668,10.428375,10.348114,3.410466,5.818771,4.994215,3.231332,8.454037,9.113081,...,9.645362,8.165754,10.437188,10.444397,10.552438,10.366699,9.446728,11.132207,fecB,fecB
NP_418711.1,11.8568,11.936009,12.245965,12.122647,4.041919,7.580954,5.93472,3.332138,10.103915,10.728151,...,11.013477,9.598895,12.28676,12.463531,12.712158,12.375125,11.412617,13.360405,fecA,fecA
NP_418715.2,9.243527,9.13265,8.876887,2.483091,2.591068,5.776036,3.031237,2.731799,6.411205,9.561881,...,3.570697,5.948192,1.962973,4.442347,3.409146,2.53659,2.259737,6.284367,yjhU,yjhU
NP_418734.1,10.764036,6.844401,10.480789,3.903688,10.651298,7.108742,4.134336,3.372682,7.567129,6.513472,...,5.118705,8.975705,7.882159,6.622633,6.800053,5.837671,4.195776,7.37479,fimA,fimA
NP_418766.4,8.649759,8.455171,8.155667,2.233634,2.609229,5.021934,2.678551,2.233634,4.379501,3.79533,...,2.819762,3.20453,1.721992,8.982187,9.156114,8.201235,7.861264,8.626945,NaN,NaN
NP_418768.1,9.541116,9.731031,9.120944,2.179949,2.555544,4.902405,2.826866,2.179949,4.625453,4.498038,...,3.754071,3.360832,2.042409,12.223248,12.400956,11.153396,10.907131,10.780787,NaN,NaN
NP_418769.1,10.196736,10.332712,9.788019,2.323821,2.964148,5.124298,3.171544,2.02656,4.821428,4.091774,...,3.761705,3.596348,2.540263,10.557312,10.679204,10.056702,9.662033,9.980459,NaN,NaN
NP_418770.2,11.259726,11.604011,10.063312,2.932114,2.890191,5.894278,3.699605,2.86614,5.075097,4.247096,...,3.251283,3.231329,2.656798,10.204533,10.402196,10.773785,10.424853,10.293843,NaN,NaN
NP_418771.1,8.540691,8.76221,8.190937,2.249965,2.77546,4.694507,2.736008,2.249965,4.207292,3.330184,...,2.816594,2.49946,2.00047,7.939263,8.291445,7.58082,7.316302,7.558822,NaN,NaN
NP_418775.1,13.703752,8.631116,7.824112,4.85889,12.287316,8.122013,12.268586,11.145634,7.640184,6.90179,...,7.318503,10.116579,10.550277,6.899878,6.454856,6.267236,5.310802,10.31957,NaN,NaN
NP_418802.1,8.847252,9.129465,8.75512,7.751157,3.147074,5.515177,3.776949,2.418709,6.508953,9.60194,...,4.010454,2.11735,3.42618,4.39447,3.803128,2.80551,3.199773,6.194795,NaN,NaN
YP_009518741.1,6.427801,6.794972,6.802893,10.75234,3.089822,4.946999,3.009548,2.714228,7.661076,10.676916,...,2.617728,2.843398,8.120426,4.302627,3.823101,2.989355,2.585057,4.174792,ykfC,ykfC

In [27]:
top50

,,,NP_414557.1,NP_415089.1,NP_415097.1,NP_415114.1,NP_415501.1,NP_415503.1,NP_415504.1,NP_415507.2,...,NP_418715.2,NP_418734.1,NP_418766.4,NP_418768.1,NP_418769.1,NP_418770.2,NP_418771.1,NP_418775.1,NP_418802.1,YP_009518741.1
gene_name,,,,,,,,,,,,,,,,,,,,,
NaN,11.494447,10.052129,9.190251,8.954854,12.292055,9.190251,7.124615,5.552765,6.056979,4.82474,...,9.243527,10.764036,8.649759,9.541116,10.196736,11.259726,8.540691,13.703752,8.847252,6.427801
NaN,12.463901,10.010634,10.089357,8.439997,11.929412,10.089357,6.868698,5.334338,5.72348,4.595991,...,9.13265,6.844401,8.455171,9.731031,10.332712,11.604011,8.76221,8.631116,9.129465,6.794972
NaN,11.558196,10.09562,9.202928,8.616248,11.33729,9.202928,7.850834,6.373494,7.054481,5.965734,...,8.876887,10.480789,8.155667,9.120944,9.788019,10.063312,8.190937,7.824112,8.75512,6.802893
NaN,4.739267,1.852114,2.01185,3.011263,5.975237,2.01185,3.069585,3.089241,3.000285,3.36721,...,2.483091,3.903688,2.233634,2.179949,2.323821,2.932114,2.249965,4.85889,7.751157,10.75234
NaN,3.613003,2.377609,8.210039,3.239484,3.267677,8.210039,10.364782,8.974326,10.397632,9.757511,...,2.591068,10.651298,2.609229,2.555544,2.964148,2.890191,2.77546,12.287316,3.147074,3.089822
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,8.418249,3.766356,8.852799,10.615852,9.997071,8.852799,7.384987,5.474669,6.117749,4.339112,...,3.409146,6.800053,9.156114,12.400956,10.679204,10.402196,8.291445,6.454856,3.803128,3.823101
NaN,9.778124,2.453486,8.932849,11.641987,10.27914,8.932849,7.675231,5.417022,5.881904,4.342689,...,2.53659,5.837671,8.201235,11.153396,10.056702,10.773785,7.58082,6.267236,2.80551,2.989355
NaN,8.927992,2.36554,8.904137,11.427354,10.394709,8.904137,7.757343,5.604204,5.969419,4.54754,...,2.259737,4.195776,7.861264,10.907131,9.662033,10.424853,7.316302,5.310802,3.199773,2.585057
NaN,8.729612,7.5808,9.838256,6.247987,9.77451,9.838256,7.425473,5.000135,6.116805,3.764245,...,6.284367,7.37479,8.626945,10.780787,9.980459,10.293843,7.558822,10.31957,6.194795,4.174792
NaN,NaN,NaN,insL-1,borD,ompT,insL-2,etk,gfcE,gfcD,gfcA,...,yjhU,fimA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ykfC

In [20]:
genes

NameError: name 'genes' is not defined